### ISSUE TITLE
[NV-1472] More than one digest step is not working properly

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#2699]
Short term workaround for this is to disable second digest step in workflow

Here first digest is of 60 seconds and second is of 60 minutes, both are of regular type.

To reproduce: 

1\. Fire 3 events in quick succession
2\. After a minute, receive in-app notification
3\. Digest begins for the email notification
4\. Fire 5 events in quick succession
5\. Wait a minute (and longer), no in-app notification for the second in-app digest

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1472](https://linear.app/novu/issue/NV-1472/more-than-one-digest-step-is-not-working-properly)</sub>

**Comment by scopsy** [comment]
@oba2311 could you elaborate on why this is blocking [NV-1593](https://linear.app/novu/issue/NV-1593/🚀-feature-sending-daily-digest-at-a-fixed-time) ? I don't see any reason for it to block the other ticket.

**Comment by oba2311** [comment]
@scopsy - how common it is that we have more than 1 digest node? sounds odd to me and seems like we have been working on this for quite some time.

**Comment by scopsy** [comment]
Seems like we have 3 different people talked about this (see attached conversations by Pawan). Right now we should either fix it, or disable the ability to add a second digest node.

**Comment by scopsy** [comment]
This is usefull when you want to: Daily Emails, but hourly in apps, I think the use case makes sense to me. We can further improve it with [NV-1593](https://linear.app/novu/issue/NV-1593/🚀-feature-sending-daily-digest-at-a-fixed-time) as it might be related and users trying to achieve this with this pattern

**Comment by oba2311** [comment]
Oh in that case if it helps with daily hourly - then def worth it.

**Comment by tsssdev** [comment]
I have fixed this as part of #2727 , created draft PR, please have look at it. the code committed working perfectly for multiple digest steps.

**Comment by oba2311** [comment]
@p-fernandez  @scopsy  LMK WDYT as I'm looking to wrap up the project this ticket is part of 😃

**Comment by scopsy** [comment]
this one still not done, Unfortuently we can't merged #2727 as is. We would need to either restructure it in smaller PR's or have @p-fernandez work on it as a standalone. Until then we won't be able to close this issue

**Comment by oba2311** [comment]
Thanks @scopsy .

I had a chat with @p-fernandez  who explained the same. I'd suggest that we sync and decide on what's next after Pablo is done with the E2E testing (we need to stop for a sec to estimate ROI on this).

**Comment by huberzeljko** [comment]
Hey, was this ever implemented?

**Comment by scopsy** [comment]
HI @huberzeljko un-fortuently not 🙏
