### ISSUE TITLE
Some margin issue on Setting page of web app

### ISSUE THREAD

**Issue by kymppi** [novuhq/novu#744]
**Describe the bug**
There seems to be some margin/padding issue on the web apps settings page.

**To Reproduce**
1. Go to https://web.novu.co
2. Reduce resolution to 1200px~
3. Click on Settings
4. Click on In App Center
5. See horizontal scrollbar appear

**Expected behavior**
It should not have a horizontal scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/48528700/176284311-4a7e3910-8350-490d-b0fd-d87e8d94a4d0.png)
![image](https://user-images.githubusercontent.com/48528700/176284336-138cf5ee-ea40-4e2e-9fec-efffdec50e01.png)

**Details (please complete the following information):**
 - OS: Windows
 - Browser: Firefox (101.0.1)

**Additional context**

**Comment by Ciggzy1312** [comment]
I can give this a try

**Comment by scopsy** [comment]
Hi @Ciggzy1312 sure thing! Aassigned you

**Comment by scopsy** [comment]
Hi @Ciggzy1312 how is it going? Do you need some help? Would love to jump on board to help or in other case let me know if you want me to un-assign you 🙏

**Comment by Ciggzy1312** [comment]
It is not showing any horizontal scrollbar in my device at least. So probably this issue has been solved

![image](https://user-images.githubusercontent.com/65884232/182021348-af0990e7-98d6-4f00-9fc8-3c074da915c9.png)

**Comment by kymppi** [comment]
It is probably not solved, it might happen only with specific screen resolutions

**Comment by scopsy** [comment]
From the image looks like your screen width is larger thank the one on @kymppi image. could you try to reduce it a bit to approximately matches kympis screen? @Ciggzy1312

**Comment by scopsy** [comment]
Hi @Ciggzy1312 did you had a chance to take a look at this?

**Comment by scopsy** [comment]
Looks like this happens for resolutions at around 1200px and the code snippet is just to high on width. Updated the description for this

**Comment by davidsoderberg** [comment]
@adarshajit I have assigned you now, just reach out to us if you need help 😄

**Comment by MohammedBajuaifer** [comment]
Hi @davidsoderberg, is this issue still open? i would like to give it a try if so

**Comment by davidsoderberg** [comment]
@MohammedBajuaifer there is someone that is already working at this one...
