### ISSUE TITLE
In App template editor input glitches

### ISSUE THREAD

**Issue by noftaly** [novuhq/novu#914]
**Describe the bug**
When creating an In-App Notification template, the input where you write your notification content makes you write right-to-left.
Everytime you enter a character, it places your cursor back to the beginning of the input

**To Reproduce**
1. Go to https://web.novu.co/templates/create
2. Create an in-app template
3. Try to write in the notification input ("Write your notification content here...")
4. See bug

**Expected behavior**
It should let you type normally

**Screenshots**

https://user-images.githubusercontent.com/34779161/181476316-a43ac400-9629-4216-9892-8c4b4c77a78d.mp4

**Details (please complete the following information):**
 - OS: macOS
 - Browsers: Safari 15.5, Firefox 104

**Comment by scopsy** [comment]
@djabarovgeorge could you check that? Was quite sure this was already resolved and the test seem to pass normally for that :o

**Comment by LetItRock** [comment]
hi @scopsy! 
yes, this is still happening in Safari, but not in Chrome:

Safari:

https://user-images.githubusercontent.com/2607232/181861208-0959635f-3b4a-4f94-ae11-0e727fd56269.mov

Chrome:

https://user-images.githubusercontent.com/2607232/181861224-d10e3fe5-87d8-4a96-a650-81dc8ede6e7f.mov

I'll take a look in to this if you don't mind ;)

**Comment by scopsy** [comment]
@LetItRock would really appreciate it! Please let me know if you would need some help with it there. Available here or on Discord 🙏

**Comment by oba2311** [comment]
Hi, @LetItRock ,  we are always here to help if needed.

**Comment by scopsy** [comment]
Merged this! Thanks @LetItRock for your contribution 🙏
